(function(){var t=document.querySelector('.nav-toggle'),l=document.querySelector('.nav-links');if(t&&l){t.addEventListener('click',function(){var o=l.classList.toggle('open');t.setAttribute('aria-expanded',o)})}
document.querySelectorAll('a[href^="#"]').forEach(function(a){a.addEventListener('click',function(e){var t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});if(l&&l.classList.contains('open')){l.classList.remove('open');t.setAttribute('aria-expanded','false')}}})});
var h=document.getElementById('siteHeader');if(h){addEventListener('scroll',function(){h.classList.toggle('scrolled',scrollY>8)},{passive:true})}
var PREVIEW=true;
var f=document.getElementById('quote-form');if(f){f.addEventListener('submit',function(e){e.preventDefault();var n=f.name.value.trim(),p=f.phone.value.trim(),m=f.message.value.trim(),note=f.querySelector('.form-note');if(!n||!p||!m){note.textContent='Please fill in your name, phone, and message.';return}if(p.replace(/\D/g,'').length<7){note.textContent='That phone number looks too short — please double-check.';return}if(PREVIEW){note.textContent='Thanks '+n.split(' ')[0]+'! (Design preview — this form goes live when the site launches.)';return}note.textContent='Thanks '+n.split(' ')[0]+'! We will call you back shortly.';f.reset()})}
var dots=Array.prototype.slice.call(document.querySelectorAll('.dot')),reviews=Array.prototype.slice.call(document.querySelectorAll('.review')),cur=0;function show(i){if(!reviews.length)return;cur=(i+reviews.length)%reviews.length;reviews.forEach(function(r,j){r.classList.toggle('active',j===cur)});dots.forEach(function(d,j){d.classList.toggle('active',j===cur)})}
dots.forEach(function(d,i){d.addEventListener('click',function(){show(i)})});if(reviews.length>1){setInterval(function(){show(cur+1)},6000)}
var y=document.getElementById('year');if(y){y.textContent=new Date().getFullYear()}
var tabs=Array.prototype.slice.call(document.querySelectorAll('.tab'));tabs.forEach(function(tab){tab.addEventListener('click',function(){tabs.forEach(function(o){o.classList.remove('active');o.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');document.querySelectorAll('.tab-panel').forEach(function(p){p.hidden=p.id!=='panel-'+tab.dataset.tab})})});
})();